### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by hxgdzyuyi** [dexteryy/OzJS#2]
1 ozma 有个optimist的依赖 不知道能会否支持一下 package.json 标准从而可以直接用 npm install -g 安装. 
2 ozma 里头关于require('../oz') 寻找js的oz库的部分能否写成ozconfig.json的配置文件 这样可以更灵活～ https://github.com/dexteryy/OzJS/blob/master/tools/ozma.js#L8

**Comment by dexteryy** [comment]
1正在做呀
2我刚才合并到gondor时也遇到这个问题，解决方法是在tools下建了一个oz的目录，fabfile里写的是：

``` python
def js():
    """Compile JS."""
    local("./tools/oz/tools/ozma.js public/js/dist/gondor.js")
```

确实不太方便，正在跟npm打包一起解决
